-- AlterTable
ALTER TABLE "categories" ADD COLUMN     "vat_rate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "sale_items" ADD COLUMN     "cogs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "unit_cost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vat_amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vat_rate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "sales" ADD COLUMN     "gross_profit" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_cogs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_vat" DOUBLE PRECISION NOT NULL DEFAULT 0;
